### ISSUE TITLE
shapearea field vs shape_area field 

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/GISquirrel#16]
Question / issue from Derrick Carlson

> I have been using GISquirrel for about a week, and am wondering if there is anyway to make the default field name for Shape_Area stored in the MS SQL database.  As it is now when a feature is imported into the MS SQL Express 2014 database the field that holds the area and length of a polygon feature are called shapearea and shapelength.  When an edit session is started and the data is put into a temp geodatabase the field names become shape_area and shape_length.  Any labels that use either of these fields fail.  Any way to keep these names the same.

**Comment by CrispinF** [comment]
@HartmutT can you check - is the field name configurable?

**Comment by DerrickDFS** [comment]
I renamed the two fields after they were imported to shape_area and shape_length.  Now things work as expected.

**Comment by CrispinF** [comment]
@DerrickDFS I've not tested this myself, but could you test whether these fields are correctly updated in the SQL database table with the length and area for edited and new features?

**Comment by HartmutT** [comment]
These field names are culture specific resources, so they are not user configurable.
"Shape_Area" and "Shape_Length" are the default names of ESRI's built-in system fields of geodatabase feature classes. These are not standard attribute fields but automatically added to a new geodatabase feature class. This includes the edit feature class in the temporary editing workspace (file geodatabase). Its "Shape_Area" and "Shape_Length" fields are not copies of the similarly named database columns, but added by ArcGIS upon creating the feature class. GISquirrel's field names were deliberatley chosen differ from ESRI's system field names in order to avoid duplicate field names in the temporary editing feature class.
However, the GISquirrel "shapearea" and "shapelength" fields are actually removed from the field list from which the fields of the editing feature class are created. So it should be possible to allow user configuration of these field names, but that would require some code changes.

**Comment by DerrickDFS** [comment]
Thanks, I noticed this and am working on another solution to my problem.

*Derrick Carlson*

*GIS Analyst*

*Drake Forestry Services Ltd.*

*1936 Bayview Crt*

*Kelowna, BC, V1Z 3L8*

*Cell: (250) 469-0142*

**Comment by CrispinF** [comment]
@HartmutT no action seems needed on this issue - agreed?

**Comment by DerrickDFS** [comment]
Thanks, I have come up with a solution for this.

*Derrick Carlson*

*GIS Analyst*

*Drake Forestry Services Ltd.*

*1936 Bayview Crt*

*Kelowna, BC, V1Z 3L8*

*Cell: (250) 469-0142*
