### ISSUE TITLE
GISquirrel with PostGIS: geometry type mismatch on save

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/GISquirrel#22]
This support question has been raised by a user:

> Hello! I've looked through the support and FAQ's, but I can't seem to figure out what i'm doing wrong when attempting to copy features from a file geodatabase-driven feature class into a GISquirrel feature class.
> 1.	I have a GISquirrel feature class that is valid and imported into ArcMap. The feature class admin reports the geometry of this table as 'Polygon'
> 2.	I have another feature class that resides in a standard file geodatabase. The properties of this layer are reported as "Feature Type: Simple; Geometry Type: Polygon".
> 3.	I copy a single polygon with 4 vertices from the fgdb-FC and paste it into the GISquirrel FC. It pastes successfully.
> 4.	When I try to save my edits, i get the error 
> 1.	"Error: 22023" Geometry type (Multipolygon) does not match the column type (Polygon)
> 5.	I'm not sure why I'm getting this error about multipolygons if my geometry types are matching. If I make the PostGIS table in question multi-part, I can save this feature successfully even though GISquirrel reports the geometry as 'Polygon'
> Do my PostGIS tables need to be multi-part in order to save any new features into them, even if they are simple polygons?
> Thank you!
>

**Comment by CrispinF** [comment]
All edits to polygons and lines in ArcGIS are saved back as MULTIPOLYGON or MULTILINESTRING respectively, so yes, your data store (in your case PostGIS) needs to be set up for this.
If you use the Import tool in GISquirrel on a fGDB layer you should find it comes into the database correctly, given an example to emulate.
@HartmutT anything to add?

**Comment by HartmutT** [comment]
ArcGIS does not distinguish between single and multi geometry types. The ArcGIS Polygon type includes both OGC Polygon and MultiPolygon; the ArcGIS Polyine type both OGC Linestring and MultiLinestring. The only exception is the MultiPoint type, which is used for special purposes such as efficient point cloud representation. Thus, any ArcGIS Polygon or Polyline edit session may create both single or multi geometries and since multi types can handle geometries of the corresponding single type but not the other way around, geometry tables must be created with MultiPolygon and MulitLinestring types and GISquirrel saves polygons and polylines as multi-geometries to comply with geometry types/constraints.
