### ISSUE TITLE
UUID field in PostgreSQL problem

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/GISquirrel#24]
A user has asked:

> I'm using a postgresql db back end with GISquirrel.  Once we've imported our layer into the database, I added a "unit_id" column, of type uuid, and I'm generating UUIDS using uuid_generate_v4() on the database side things.  But, when we add a new shape on the map in ArcGIS, it's automatically getting a unit_id of all zeros, instead of the generated one. It looks like ArcGis is trying to generate the UUID, rather than not touching the field and letting the database handle it.  Can you give any recommendation on how to fix this?

**Comment by HartmutT** [comment]
Features created in a GISquirrel edit session are native ArcGIS features with .Net attribute types. The .Net equivalent of a PostgreSQL Uuid is a Guid and it happens to be a value type, i.e. it is not nullable but always has a value and its default value is all zeros. When this is uploaded to PostgreSQL, uuid_generate_v4()  isn’t called or doesn’t do anything (is it the default value or a trigger?) because it sees the column as already populated.
If uuid_generate_v4() is the PostgreSQL default value it cannot be directly applied to features created in ArcGIS because it is a database function that ArcGIS and .Net don’t understand (GISquirrel does transfer fixed default values to the editing FGDB feature class). One solution would be a trigger function in the database that recognised and overwrote  empty Uuids. Another would be GISquirrel doing this, replacing empty Guids with null when uploading. This is not straightforward though, because (1) the insert statements are and very much should be parameterised and the parameter for a Uuid column is a .Net Guid, which isn’t nullable; and (2) a null value may violate null constraints on the PostgreSQL table. I’ll look into this.

**Comment by CrispinF** [comment]
It is possible that simply hiding the "unit_id" guid column in the map layer will fix this, as it will prevent ArcMap from adding the default value during the edit session, and postGIS should add it on saving.  We've not yet tested and confirmed this, but will soon.

**Comment by CrispinF** [comment]
It was confirmed that hiding the uuid/guid column in ArcMap resolved this issue.
