### ISSUE TITLE
Saving MXD during an editing session loses edits

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/GISquirrel#25]
Reported by Thomas Weiss:

> It appears that when we have an editing session open, if we save the map document (mxd), the temporary file geodatabase is immediately destroyed and all of our edits are lost. Is there a way to stop this from happening?

**Comment by CrispinF** [comment]
This is puzzling, as we cannot think of any reason this would happen.  There’s no reason the temporary editing layers should be lost. We wonder whether perhaps this user has some customisation that cleans up such things on saving?

**Comment by HartmutT** [comment]
When the map document is saved during an edit session, ArcMap raises the same event as when the application or the current map document is closed. In order to prevent data loss, GISquirrel listens for this event and in response calls its end of edit session code. This will prompt to save any pending edits and if the user presses OK, will save them to the original data source before ArcMap closes. So there should be no data loss unless the edits are expressly discarded by the user, presumably because the map document was saved before the edits were ready to be  committed. We could avoid this potential dilemma by disabling the "save map document" command during a GISquirrel edit session.
If the question is whether the temporary editing data source may be kept alive beyond the life span of the map document, potentially returning to a previous edit session, the answer is no. The editing workspace is a scratch workspace that only exists during the ArcMap session in which it was created.

**Comment by CrispinF** [comment]
Thanks @HartmutT I think we should make no changes in response to this report, as we cannot replicate the issue. But keeping this issue open for now.

**Comment by CrispinF** [comment]
Not reported since, so closing.
